name: Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-isocalendar.svg
          user: seungdori
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Seoul
          config_output: svg
          config_padding: 5%
